[package]
name = "number_to_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
ctrlc = "3.4.1"
clap = { version = "4.5.21", features = ["derive"] }
